<<<<<<< HEAD
# Generated by Django 3.2.8 on 2021-11-04 18:37
=======
# Generated by Django 3.2.8 on 2021-11-04 13:57
>>>>>>> master

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('patient', '0001_initial'),
        ('employee', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
<<<<<<< HEAD
=======
            name='Breed',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('animal', models.CharField(choices=[('Dog', 'Dog'), ('Cat', 'Cat'), ('Bird', 'Bird'), ('Reptile', 'Reptile'), ('Rabbit', 'Rabbit'), ('Fish', 'Fish'), ('Unknown', 'Unkown')], default='Unknown', max_length=50)),
                ('breed', models.CharField(default='Unknown', max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Owner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('phone', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Veterinary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vet_name', models.CharField(max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pet_name', models.CharField(max_length=200)),
                ('animal_type', models.CharField(choices=[('Dog', 'Dog'), ('Cat', 'Cat'), ('Bird', 'Bird'), ('Reptile', 'Reptile'), ('Rabbit', 'Rabbit'), ('Fish', 'Fish'), ('Unknown', 'Unkown')], default='Unkown', max_length=50)),
                ('age', models.IntegerField(default=0)),
                ('breed', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vetoffice.breed')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vetoffice.owner')),
            ],
            options={
                'ordering': ['owner'],
            },
        ),
        migrations.CreateModel(
>>>>>>> master
            name='Appointment',
            fields=[
                ('appointmentID', models.BigAutoField(primary_key=True, serialize=False)),
                ('employeeID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='employee.employee')),
                ('patientID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='patient.patient')),
            ],
        ),
    ]
