# Generated by Django 3.2.8 on 2021-11-04 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vetoffice', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Breed',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('animal', models.CharField(choices=[('DOG', 'Dog'), ('CAT', 'Cat'), ('BIRD', 'Bird'), ('REPTILE', 'Reptile'), ('RABBIT', 'Rabbit'), ('FISH', 'Fish'), ('UNKOWN', 'unkown')], default='Unknown', max_length=50)),
                ('breed', models.CharField(default='Unknown', max_length=200)),
            ],
        ),
        migrations.AlterField(
            model_name='patient',
            name='animal_type',
            field=models.CharField(choices=[('DOG', 'Dog'), ('CAT', 'Cat'), ('BIRD', 'Bird'), ('REPTILE', 'Reptile'), ('RABBIT', 'Rabbit'), ('FISH', 'Fish'), ('UNKOWN', 'unkown')], default='Unkown', max_length=50),
        ),
    ]
