# Generated by Django 3.2.8 on 2021-10-18 21:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vetoffice', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patient',
            name='animalType',
        ),
        migrations.AddField(
            model_name='patient',
            name='animal_type',
            field=models.CharField(choices=[('Dog', (('german sheperd', 'German Sheperd'), ('pomeranian', 'Pomeranian'), ('labrador', 'Labrador'), ('husky', 'Husky'), ('bulldog', 'Bulldog'), ('chihuahua', 'Chihuahua'))), ('Cat', (('norewgian forest cat', 'Norwegian Forest Cat'), ('persian', 'Persian'), ('sphynx', 'Sphynx'), ('siamese', 'Siamese'), ('maine coon', 'Maine Coon'))), ('Bird', (('parakeet', 'Parakeet'), ('cockatiel', 'Cockatiel'), ('canarie', 'Canarie'), ('african grey', 'African Grey'), ('amazon parrot', 'Amazon Parrot'))), ('Reptile', (('crested gecko', 'Crested Gecko'), ('ball python', 'Ball Python'), ('bearded dragon', 'Bearded Dragon'), ('leopard gecko', 'Leopard Gecko'), ('corn snake', 'Corn Snake'))), ('Rabbit', (('mini rex', 'Mini Rex'), ('holland lop', 'Holland Lop'), ('dutch lop', 'Dutch Lop'), ('dwarf hotot', 'Dwarf Hotot'), ('mini lop', 'Mini lop'))), ('Fish', (('betta', 'Betta'), ('goldfish', 'Goldfish'), ('angelfish', 'Angelfish'), ('catfish', 'Catfish'), ('guppi', 'Guppi'))), ('Unknown', 'unkown')], default='Unkown', max_length=200),
        ),
    ]
