# Generated by Django 3.2.8 on 2021-10-25 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vetoffice', '0002_auto_20211018_2158'),
    ]

    operations = [
        migrations.AlterField(
            model_name='owner',
            name='first_name',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='owner',
            name='last_name',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='patient',
            name='animal_type',
            field=models.CharField(choices=[('Dog', 'dog'), ('Cat', 'cat'), ('Bird', 'bird'), ('Reptile', 'reptile'), ('Rabbit', 'rabbit'), ('Fish', 'fish'), ('Unknown', 'unkown')], default='Unkown', max_length=50),
        ),
    ]
