# Generated by Django 3.2.8 on 2021-11-05 16:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='animal',
            options={'ordering': ['animal_type']},
        ),
        migrations.AlterModelOptions(
            name='breed',
            options={'ordering': ['animal']},
        ),
        migrations.AlterField(
            model_name='patient',
            name='breed',
            field=models.ForeignKey(limit_choices_to={False}, on_delete=django.db.models.deletion.CASCADE, to='patient.breed'),
        ),
    ]
