# Generated by Django 3.2.8 on 2021-11-11 15:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0002_alter_patient_breed'),
    ]

    operations = [
        migrations.RenameField(
            model_name='patient',
            old_name='animal_type',
            new_name='animal',
        ),
        migrations.AlterField(
            model_name='patient',
            name='breed',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='patient.breed'),
        ),
    ]
